# action.yaml
name: "Isolated changes"
description: "This action allows you to isolate changes for a PR to a specific folder. Useful if you want migrations to be merged and deployed in isolation from other changes."
inputs:
  isolate_folder:
    description: "The folder you would like to isolate"
    default: "migrations"
  ref_from:
    description: "ref to run from"
    default: "${{ github.base_ref }}"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.isolate_folder }}
    - ${{ inputs.ref_from }}
